version: '3'

services:
  vpn:
    image: podpalch/vpn-anyconnect-docker
    container_name: vpn
    build:
      context: .
    environment:
      - ANYCONNECT_SERVER=${ANYCONNECT_SERVER}
      - ANYCONNECT_USER=${ANYCONNECT_USER}
      - ANYCONNECT_PASSWORD=${ANYCONNECT_PASSWORD}
    networks:
      - default
    privileged: true
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    security_opt:
      - label:disable
    dns: 8.8.8.8
    dns_search: ${DNS_SUFFIX}
    dns_opt:
      - ndots:1
  
#  packer:
#    container_name: packer
#    image: alpine
#    tty: true
#    entrypoint: /bin/sleep 10
#    depends_on:
#      - vpn
#    network_mode: "service:vpn"

